# Generated by Django 5.2.14 on 2026-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
