# Generated by Django 5.2.14 on 2026-05-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizquestion_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='title',
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
